kind: Service
apiVersion: v1
metadata:
  name: xkucharp-ambulance-hr-ufe   #  určuje aj záznam DNS v rámci virtuálne siete klastra
spec:
  selector:
    pod: xkucharp-ambulance-hr-ufe-label     # zhoduje sa s metadata.labels šablóny pod-u
  ports:
    - name: http
      protocol: TCP
      port: 80            # port pomenovanej služby, môže sa líšiť
      # od portu na ktorom počúva kontajner
      targetPort: http    # viď meno portu v deployment.yaml