apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: patrikkuchar/ambulance-hr-ufe
    newName: patrikkuchar/ambulance-hr-ufe
    newTag: 1.0.1  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú

replacements:
  - targets:
      - select:
          group: fe.milung.eu
          version: v1
          kind: WebComponent
          name: xkucharp-ambulance-hr-ufe
        fieldPaths:
          - spec.hash-suffix
    source:
      version: v1
      kind: Deployment
      name:  xkucharp-ambulance-hr-ufe-deployment
      fieldPath: spec.template.spec.containers.0.image
      options:
        delimiter: ':'
        index: 1