apiVersion: v1
kind: Secret
metadata:
  name: repository-pat
  namespace: wac-hospital

type: Opaque
stringData:
  username: "patrikkuchar" # zvyčajne môže byť akékoľvek meno
  password: "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"  # vygenerovaný PAT